version: '3'
services:
    php-apache:
        image: php:7.2.1-apache
        expose:
            - "80"
        volumes:
            - ./app:/var/www/html:z
            - ./additional:/additional:z
        labels:
            - traefik.enable=true
            - traefik.backend=$LABEL
            - traefik.docker.network=traefik_default
            - traefik.frontend.rule=Host:$URL



