version: '3'
services:
    php-apache:
        image: php:7.2.1-apache
        expose:
            - "80"
        volumes:
            - ./laraapp:/var/www/html:z
            - ./additional/000-default.conf:/etc/apache2/sites-available/000-default.conf:z
        networks:
            - traefik_default
        labels:
            - traefik.enable=true
            - traefik.backend=$LABEL
            - traefik.docker.network=traefik_default
            - traefik.frontend.rule=Host:$URL
        
networks:
    traefik_default:
        external: true


